### ISSUE TITLE
离谱bug

### ISSUE THREAD

**Issue by zhiziqixingdeng** [NIHAOAWA/-#2]
cout<<work();改为work(),自定义函数没学明白啊，而且应该有一bool变量来截取，bool towork，然后towork=work(),好好学学cpp吧

**Comment by zhiziqixingdeng** [comment]
而且输入bool类型，你是要弄死客户shi ba

**Comment by zhiziqixingdeng** [comment]
而且if判断不用，直接返回更节省时间

**Comment by zhiziqixingdeng** [comment]
我最近用不了电脑，只能用平板连机械硬盘

**Comment by zhiziqixingdeng** [comment]
弄错了，键盘

**Comment by zhiziqixingdeng** [comment]
所以，你可以成为bug之神

**Comment by zhiziqixingdeng** [comment]
如果是bool类型的话，cout只能输出0,1.如果用户不会c++怎么办

**Comment by NIHAOAWA** [comment]
嗯
